import Head from 'next/head';
import { BsGraphUpArrow } from 'react-icons/bs';
import { GoRocket } from 'react-icons/go';
import Link from 'next/link';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=1190" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="inner flex space-between align-center">
          <GoRocket color="#111" size={36} />
          <div className="account">
            <Link href="sign-in">Sign In</Link>
            <Link href="sign-up">Get started</Link>
          </div>
        </div>
      </header>

      <div className="banner">
        <div className="inner">
          <h1>The Log...</h1>
          <p>
            Discover stories, thinking, and expertise from writers on any topic.
          </p>
        </div>
      </div>

      <article className="trend">
        <div className="inner">
          <h2>
            <BsGraphUpArrow size={20} />
            Trending on Log
          </h2>
          <ul>
            <li />
            <li />
            <li />
            <li />
            <li />
            <li />
          </ul>
        </div>
      </article>

      <article className="category">
        <div className="inner">
          <h2>Discover more of what matters to you</h2>
          <ul>
            <li>ASSASSINS</li>
            <li>FIGHTERS</li>
            <li>MAGES</li>
            <li>MARKSMEN</li>
            <li>SUPPORTS</li>
            <li>TANKS</li>
            <li>MEWS</li>
            <li>DISCOVER</li>
            <li>COMMUNITY</li>
            <li>LEAGUE</li>
            <li>LEGENDS</li>
            <li>DISCORD</li>
          </ul>
          <a href="/category">See more category</a>
        </div>
      </article>

      <article className="topic">
        <div className="inner">
          <div className="topic-card">
            <div className="author-name">GWEN</div>
            <div className="topic-title">THE HALLOWED SEAMSTRESS</div>
            <div className="topic-desc">
              A former doll transformed and brought to life by magic, Gwen
              wields the very tools that once created her. She carries the
              weight of her maker's love with every step, taking nothing for
              granted. At her command is the Hallowed Mist, an ancient and...
            </div>
            <div className="topic-created">yyyy/mm/dd</div>
          </div>
          <div className="topic-card">
            <div className="author-name">IRELIA</div>
            <div className="topic-title">THE BLADE DANCER</div>
            <div className="topic-desc">
              The Noxian occupation of Ionia produced many heroes, none more
              unlikely than young Irelia of Navori. Trained in the ancient
              dances of her province, she adapted her art for war, using the
              graceful and carefully practised movements to levitate a host
              of...
            </div>
            <div className="topic-created">yyyy/mm/dd</div>
          </div>
          <div className="topic-card">
            <div className="author-name">Anivia</div>
            <div className="topic-title">THE CRYOPHOENIX ANIVIA</div>
            <div className="topic-desc">
              Outside the gleaming city of Demacia, the stone colossus Galio
              keeps vigilant watch. Built as a bulwark against enemy mages, he
              often stands motionless for decades until the presence of powerful
              magic stirs him to life. Once activated, Galio makes the...
            </div>
            <div className="topic-created">yyyy/mm/dd</div>
          </div>
        </div>
      </article>
    </>
  );
}
